##################################################################
# CREATE IP ila_td400_s4096_cap
##################################################################

set ila_td400_s4096_cap [create_ip -name ila -vendor xilinx.com -library ip -version 6.2 -module_name ila_td400_s4096_cap]

set_property -dict {
  CONFIG.C_PROBE0_WIDTH {400}
  CONFIG.C_DATA_DEPTH {4096}
  CONFIG.C_NUM_OF_PROBES {1}
  CONFIG.Component_Name {ila_td400_s4096_cap}
  CONFIG.C_TRIGOUT_EN {false}
  CONFIG.C_EN_STRG_QUAL {1}
  CONFIG.C_PROBE63_MU_CNT {2}
  CONFIG.C_PROBE62_MU_CNT {2}
  CONFIG.C_PROBE61_MU_CNT {2}
  CONFIG.C_PROBE60_MU_CNT {2}
  CONFIG.C_PROBE59_MU_CNT {2}
  CONFIG.C_PROBE58_MU_CNT {2}
  CONFIG.C_PROBE57_MU_CNT {2}
  CONFIG.C_PROBE56_MU_CNT {2}
  CONFIG.C_PROBE55_MU_CNT {2}
  CONFIG.C_PROBE54_MU_CNT {2}
  CONFIG.C_PROBE53_MU_CNT {2}
  CONFIG.C_PROBE52_MU_CNT {2}
  CONFIG.C_PROBE51_MU_CNT {2}
  CONFIG.C_PROBE50_MU_CNT {2}
  CONFIG.C_PROBE49_MU_CNT {2}
  CONFIG.C_PROBE48_MU_CNT {2}
  CONFIG.C_PROBE47_MU_CNT {2}
  CONFIG.C_PROBE46_MU_CNT {2}
  CONFIG.C_PROBE45_MU_CNT {2}
  CONFIG.C_PROBE44_MU_CNT {2}
  CONFIG.C_PROBE43_MU_CNT {2}
  CONFIG.C_PROBE42_MU_CNT {2}
  CONFIG.C_PROBE41_MU_CNT {2}
  CONFIG.C_PROBE40_MU_CNT {2}
  CONFIG.C_PROBE39_MU_CNT {2}
  CONFIG.C_PROBE38_MU_CNT {2}
  CONFIG.C_PROBE37_MU_CNT {2}
  CONFIG.C_PROBE36_MU_CNT {2}
  CONFIG.C_PROBE35_MU_CNT {2}
  CONFIG.C_PROBE34_MU_CNT {2}
  CONFIG.C_PROBE33_MU_CNT {2}
  CONFIG.C_PROBE32_MU_CNT {2}
  CONFIG.C_PROBE31_MU_CNT {2}
  CONFIG.C_PROBE30_MU_CNT {2}
  CONFIG.C_PROBE29_MU_CNT {2}
  CONFIG.C_PROBE28_MU_CNT {2}
  CONFIG.C_PROBE27_MU_CNT {2}
  CONFIG.C_PROBE26_MU_CNT {2}
  CONFIG.C_PROBE25_MU_CNT {2}
  CONFIG.C_PROBE24_MU_CNT {2}
  CONFIG.C_PROBE23_MU_CNT {2}
  CONFIG.C_PROBE22_MU_CNT {2}
  CONFIG.C_PROBE21_MU_CNT {2}
  CONFIG.C_PROBE20_MU_CNT {2}
  CONFIG.C_PROBE19_MU_CNT {2}
  CONFIG.C_PROBE18_MU_CNT {2}
  CONFIG.C_PROBE17_MU_CNT {2}
  CONFIG.C_PROBE16_MU_CNT {2}
  CONFIG.C_PROBE15_MU_CNT {2}
  CONFIG.C_PROBE14_MU_CNT {2}
  CONFIG.C_PROBE13_MU_CNT {2}
  CONFIG.C_PROBE12_MU_CNT {2}
  CONFIG.C_PROBE11_MU_CNT {2}
  CONFIG.C_PROBE10_MU_CNT {2}
  CONFIG.C_PROBE9_MU_CNT {2}
  CONFIG.C_PROBE8_MU_CNT {2}
  CONFIG.C_PROBE7_MU_CNT {2}
  CONFIG.C_PROBE6_MU_CNT {2}
  CONFIG.C_PROBE5_MU_CNT {2}
  CONFIG.C_PROBE4_MU_CNT {2}
  CONFIG.C_PROBE3_MU_CNT {2}
  CONFIG.C_PROBE2_MU_CNT {2}
  CONFIG.C_PROBE1_MU_CNT {2}
  CONFIG.C_PROBE0_MU_CNT {2}
  CONFIG.C_TRIGIN_EN {false}
  CONFIG.ALL_PROBE_SAME_MU_CNT {2}
} [get_ips ila_td400_s4096_cap]

set_property -dict {
  GENERATE_SYNTH_CHECKPOINT {1}
} $ila_td400_s4096_cap

##################################################################

